-- 프로그래머스 조건에 맞는 개발자 찾기
SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME

FROM DEVELOPERS AS d

WHERE EXISTS (

  SELECT 1
  FROM SKILLCODES AS s
  WHERE s.NAME IN ('Python', 'C#')
    AND (d.SKILL_CODE & s.CODE) <> 0

)

ORDER BY d.ID;
